### ISSUE TITLE
[native-app] App is only showing placeholders

### ISSUE THREAD

**Issue by touficbatache** [pct-org/getting-started#4]
**Describe the bug**
When I open the app, I only see placeholders without real content. When I try to search for something, it just keeps searching without actual results. I have waited for several minutes but nothing... Maybe it's just an Android 10 issue?

**To Reproduce**
1. Open 'Popcorn Time'
2. Try to search for something

**Expected behavior**
The app should show real content like in the screenshots.

**Screenshots**
![Screenshot_20190915-231327](https://user-images.githubusercontent.com/17137918/64927077-bcc9e300-d80e-11e9-953a-50e98137b7b4.png)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3
 - OS: Android 10
 - Version 0.16.0

**Comment by touficbatache** [comment]
APIs are back up it seems. Your app is working and based on the PopcornTime TV issue's comments, all is working again.

**Comment by manu3008** [comment]
Hey @TriPSs could you please compile a new release with all the new updates?

**Comment by TriPSs** [comment]
@manu3008 The version that i'm currently working on does not work yet, as it's migrating from the public api (Witch is down again) to the local one.

**Comment by manu3008** [comment]
@TriPSs don't worry then, I'm using the legacy app for Android (.sh) for now since yours wasn't working. Wish I could do more to help man. Thanks for all the hard work.

**Comment by TriPSs** [comment]
I'm going to close this issues, since the original API moved to a other domain the old one will not work anymore.
